intent_recognizer:
    paths:
        model: "yana/static/ir/intent_model"
        intents: "yana/static/ir/intents.pkl"
        embeddings: "yana/static/ir/intent_embeddings.pkl"
        classifier: "yana/static/ir/intent_classifier.pkl"
        data: "yana/static/ir/intents.json"

speech_synthesizer:
    constants:
        wav_channels: 1       # Mono
        wav_header_size: 44   # Bytes
        wav_sample_width: 2   # 16 / 8 (2 bytes)

    params:
        model_id: "v3_en"
        language: "en"
        put_accent: True
        put_yo: True
        speaker: "en_10"
        sample_rate: 48000  # 48000, 24000, or 8000
        line_len_limit: 800
        device: "cpu"
        num_threads: 4

    urls:
        config_uri:
            "https://raw.githubusercontent.com/snakers4/silero-models/master/models.yml"
        model_uri: "https://models.silero.ai/models/tts/en/v3_en.pt"

    paths:
        config: "yana/static/latest_silero_models.yml"
        model: "yana/static/tts/tts_model.pt"

speech_recognizer:
    paths:
        user_audio: "yana/static/audio/user.wav"
        vosk_model: "yana/static/stt/vosk-small"
        whisper_model: "yana/static/stt/whisper-base.bin"
        whisper_binary: "yana/bin/whisper"

speech_listener:
    params:
        sample_rate: 16000
    paths:
        user_audio: "yana/static/audio/user.wav"

interaction:
    paths:
        intents: "yana/static/ir/intents.json"
        follow_ups: "yana/static/ir/follow_ups.json"
        responses: "yana/static/ir/responses.json"

entity_recognizer:
    paths:
        model: "yana/static/ner/ner_model"
        tokenizer: "yana/static/ner/ner_tokenizer"

database:
    path: "dev.db"
