constants:
    wav_channels: 1       # Mono
    wav_header_size: 44   # Bytes
    wav_sample_width: 2   # 16 / 8 (2 bytes)

params:
    model_id: "v3_en"
    language: "en"
    put_accent: True
    put_yo: True
    speaker: "en_10"
    sample_rate: 48000  # 48000, 24000, or 8000
    line_len_limit: 800
    device: "cpu"
    num_threads: 4

urls:
    config_uri:
        "https://raw.githubusercontent.com/snakers4/silero-models/master/models.yml"
    model_uri: "https://models.silero.ai/models/tts/en/v3_en.pt"

paths:
    config_path: "yana/static/latest_silero_models.yml"
    model_path: "yana/static/models/tts_model.pt"


